### ISSUE TITLE
Get twitch ID

### ISSUE THREAD

**Issue by pcegarra** [mkody/twitch-emoticons#2]
Hi, thanks for update this library.
Do you know if its possible to get the twitch id from a channel name?

Thanks

**Comment by mkody** [comment]
We could use the API, but you'll need to [get an Client API key](https://dev.twitch.tv/console/apps/create).
Then it's calling `https://api.twitch.tv/helix/users?login=<username>`, with the `Client-ID` header containing your key.  

I've made a quick tool if you want to use it: https://s.kdy.ch/twitchid/  
(you can lookup multiple usernames with a comma like `0kody,twitch,twitchplayspokemon`)
