### ISSUE TITLE
Error when using an example code

### ISSUE THREAD

**Issue by Stef-00012** [mkody/twitch-emoticons#26]
i used the example code to get all emotes (removed channel part
```js
const { EmoteFetcher, EmoteParser } = require('@mkody/twitch-emoticons');
const config = require(`${process.env.rootDir}/config.json`)

const fetcher = new EmoteFetcher(config.twitch.EmoteParser.clientId, config.twitch.EmoteParser.clientSecret);
const parser = new EmoteParser(fetcher, {
    template: '<img class="emote" alt="{name}" src="{link}">',
    match: /(\w+)+?/g
});

Promise.all([
    fetcher.fetchTwitchEmotes(),
    fetcher.fetchBTTVEmotes(),
    fetcher.fetchSevenTVEmotes(),
]).then(() => {
    const globalEmotes = parser.parse('EZ Clap way too easy LUL now for the last bost monkaS');
    console.log(globalEmotes);
}).catch(err => {
    console.error('Error loading emotes...');
    console.error(err);
});
```

but i get this error
```bash
Error loading emotes...
RequestError: unable to get local issuer certificate
    at ClientRequest.<anonymous> (/data/data/com.termux/files/home/twitch/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (/data/data/com.termux/files/home/twitch/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:496:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TLSSocket.onConnectSecure (node:_tls_wrap:1545:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  timings: {
    start: 1678721938987,
    socket: 1678721938989,
    lookup: 1678721940269,
    connect: 1678721940467,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1678721940604,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 1280,
      tcp: 198,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 1617
    }
  }
}
```

**Comment by mkody** [comment]
Hi!
The issue - `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` - is not directly related to this project and could happen with multiple other hosts.
I see you're trying to run this in termux (`data/data/com.termux/[...]`). I've tried it myself with a fresh install + only `nodejs` and `yarn` installed and couldn't reproduce this.
Could you try to run `pkg upgrade` to make sure all dependencies are up-to-date, restart the terminal, and try again?

Either your `ca-certificates` package isn't up-to-date, or it's using the TLS/SSL from Android and it might be too old or not up-to-date either.

**Comment by Stef-00012** [comment]
Hi, I tried running   `pkg update` (to update the repos) and `pkg upgrade` to update the packages and then i ran the code but i still get same error
and running specifically `pkg upgrade ca-certificates` says it's already at latest version
![Screenshot_20230315_145634_Termux](https://user-images.githubusercontent.com/81536172/225336668-43b45771-4693-4722-a718-98a145a0c860.png)

Bu the way I tried installing same version of `got` package (`11.8.6`) and trying to fetch `https://www.google.com` and it worked fine
![Screenshot_20230315_152117_Discord](https://user-images.githubusercontent.com/81536172/225338435-43432a5d-126e-4891-ba68-3b5ebfebcd07.png)

**Comment by mkody** [comment]
It would be interesting to try that but with the URLs from 7TV and BTTV that we try to reach, to at least know which one is having an issue:
- `https://api.betterttv.net/3/cached/emotes/global`
- `https://7tv.io/v3/emote-sets/global`

You could try with `curl -vI <URL>` too on the host for details.

**Comment by mkody** [comment]
Oh and can I know which version of node you're using? `node --version`

**Comment by Stef-00012** [comment]
I think that's the issue, the DNS was blocking the `7tv.io` URL
![Screenshot_20230315_160942_Kiwi Browser](https://user-images.githubusercontent.com/81536172/225353722-e02645fc-0f23-4f56-8431-b6380aad9ba1.png)


I just added it in the allow list, ima wait for DNS cache to update and then try again he package

**Comment by mkody** [comment]
Interesting, I use NextDNS myself and it never got caught that way
But I also don't use their CA as I've only changed my DNS-over-TLS to it.

**Comment by Stef-00012** [comment]
Yep, now it works fine
![Screenshot_20230315_161406_Discord](https://user-images.githubusercontent.com/81536172/225354723-dd4f4869-927a-4e64-b005-b084ac49c87c.jpg)

**Comment by mkody** [comment]
Glad this got resolved!
You might want to allow their domain in your NextDNS' settings so you can still use it.
![image](https://user-images.githubusercontent.com/843787/225355673-a8337e1d-ed23-4223-a15b-79e9b3bea968.png)

Have a nice evening

**Comment by Stef-00012** [comment]
(I'm not sure if this comment will reopen the issue, in case it does, you can re-close it)
However,

> Interesting, I use NextDNS myself and it never got caught that way But I also don't use their CA as I've only changed my DNS-over-TLS to it.

It was being blocked from the "1Hosts (Xtra)" blocklist
![Screenshot_20230315_161703_Kiwi Browser](https://user-images.githubusercontent.com/81536172/225356062-989d1212-6741-4f9b-b1da-4e6195a55915.png)

However I think it's cause i use <i>way too many blocklists</i>
![Screenshot_20230315_161630_Kiwi Browser](https://user-images.githubusercontent.com/81536172/225355771-fdc24e0e-5a42-498c-896f-5133cb37ca64.jpg)
