### ISSUE TITLE
Kick emotes

### ISSUE THREAD

**Issue by mnaser** [mkody/twitch-emoticons#36]
Hi there!

Dope library.  Do you think you could implement support for Kick emotes by any chance?

Thanks,

**Comment by mkody** [comment]
Hi, not really sure if I want to put that in the scope of this project, it should made into a new one. 

I want to focus here on Twitch and its 3rd parties.
Kick has its very own system and only 7TV right now.
Likewise for YouTube which is vastly different (with 7TV and Truffle for it).
 
Also they didn't "launch" their API to the public yet, right now it's officially only early registrations ([Kick Developers](https://developers.kick.com/)).
And from what I can gather around, there's nothing about fetching channel emotes right now.
